/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    CloudExecutionWorker: {
      name: string;
      type: "sst.aws.Function";
    };
    Control: {
      name: string;
      type: "sst.aws.Dynamo";
    };
    DevelopmentHttpApi: {
      type: "sst.aws.ApiGatewayV2";
      url: string;
    };
    EmptyProjectCleanup: {
      name: string;
      type: "sst.aws.Function";
    };
    ExecutionControlledEndpoint: {
      name: string;
      type: "sst.aws.Function";
    };
    Protected: {
      name: string;
      type: "sst.aws.Dynamo";
    };
    UsersProjectsApi: {
      name: string;
      type: "sst.aws.Function";
    };
  }
}

import "sst";
export {};
